
export STAY_OFF_MY_LAWN=1
NEW_PROMPT_COMMAND='[[ -n ${MIUI_BUILD_VERSION} ]] && echo -e "\\033[1;48;5;160;38;5;226m[Android 编译环境 ${TARGET_PRODUCT:-(no product)} ${TARGET_BUILD_VARIANT:-(no variant)}]\\033[0m"'
if [[ -n ${PROMPT_COMMAND} ]]; then
    PROMPT_COMMAND="${PROMPT_COMMAND}; ${NEW_PROMPT_COMMAND}"
else
    PROMPT_COMMAND="${NEW_PROMPT_COMMAND}"
fi

unset NEW_PROMPT_COMMAND

